export const GET_ORDERS_BY_COLLECTION_POINT = 'GET_ORDERS_BY_COLLECTION_POINT';
export const GET_ORDERS_BY_COLLECTION_POINT_START = 'GET_ORDERS_BY_COLLECTION_POINT_START';
export const GET_ORDERS_BY_COLLECTION_POINT_SUCCESS = 'GET_ORDERS_BY_COLLECTION_POINT_SUCCESS';
export const GET_ORDERS_BY_COLLECTION_POINT_FAIL = 'GET_ORDERS_BY_COLLECTION_POINT_FAIL';

export const UPDATE_ORDER = 'UPDATE_ORDER';
export const UPDATE_ORDER_START = 'UPDATE_ORDER_START';
export const UPDATE_ORDER_SUCCESS = 'UPDATE_ORDER_SUCCESS';
export const UPDATE_ORDER_FAIL = 'UPDATE_ORDER_FAIL';

