export const AUTH_CHECK_STATE = 'AUTH_CHECK_STATE';
export const AUTH_USER = 'AUTH_USER';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT';
export const AUTH_INITIATE_LOGOUT = 'AUTH_INITIATE_LOGOUT';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const FIND_BAR = 'FIND_BAR';
export const FIND_BAR_START = 'FIND_BAR_START';
export const FIND_BAR_SUCCESS = 'FIND_BAR_SUCCESS';
export const FIND_BAR_FAIL = 'FIND_BAR_FAIL';
export const REMOVE_BAR = 'REMOVE_BAR';
export const REMOVE_BAR_START = 'REMOVE_BAR_START';
export const REMOVE_BAR_SUCCESS = 'REMOVE_BAR_SUCCESS';
export const REMOVE_BAR_FAIL = 'REMOVE_BAR_FAIL';
