export const AUTH_CHECK_STATE = 'AUTH_CHECK_STATE';
export const AUTH_USER = 'AUTH_USER';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT';
export const AUTH_INITIATE_LOGOUT = 'AUTH_INITIATE_LOGOUT';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_STORE_TOKEN = 'AUTH_STORE_TOKEN';
export const AUTH_AUTO_LOGIN = 'AUTH_AUTO_LOGIN';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const FIND_BAR = 'FIND_BAR';
export const FIND_BAR_START = 'FIND_BAR_START';
export const FIND_BAR_SUCCESS = 'FIND_BAR_SUCCESS';
export const FIND_BAR_FAIL = 'FIND_BAR_FAIL';
export const REMOVE_BAR = 'REMOVE_BAR';
export const REMOVE_BAR_START = 'REMOVE_BAR_START';
export const REMOVE_BAR_SUCCESS = 'REMOVE_BAR_SUCCESS';
export const REMOVE_BAR_FAIL = 'REMOVE_BAR_FAIL';

export const FIND_DRINKS = 'FIND_DRINKS';
export const FIND_DRINKS_START = 'FIND_DRINKS_START';
export const FIND_DRINKS_SUCCESS = 'FIND_DRINKS_SUCCESS';
export const FIND_DRINKS_FAIL = 'FIND_DRINKS_FAIL';

export const FIND_DRINK_CATEGORIES = 'FIND_DRINK_CATEGORIES';
export const FIND_DRINK_CATEGORIES_START = 'FIND_DRINK_CATEGORIES_START';
export const FIND_DRINK_CATEGORIES_SUCCESS = 'FIND_DRINK_CATEGORIES_SUCCESS';
export const FIND_DRINK_CATEGORIES_FAIL = 'FIND_DRINK_CATEGORIES_FAIL';

export const UPDATE_BASKET = 'UPDATE_BASKET';
export const UPDATE_BASKET_START = 'UPDATE_BASKET_START';
export const UPDATE_BASKET_SUCCESS = 'UPDATE_BASKET_SUCCESS';

export const SUBMIT_ORDER = 'SUBMIT_ORDER';
export const SUBMIT_ORDER_START = 'SUBMIT_ORDER_START';
export const SUBMIT_ORDER_SUCCESS = 'SUBMIT_ORDER_SUCCESS';
export const SUBMIT_ORDER_FAIL = 'SUBMIT_ORDER_FAIL';

export const ORDER_HISTORY = 'ORDER_HISTORY';
export const ORDER_HISTORY_START = 'ORDER_HISTORY_START';
export const ORDER_HISTORY_SUCCESS = 'ORDER_HISTORY_SUCCESS';
export const ORDER_HISTORY_FAIL = 'ORDER_HISTORY_FAIL';
