export const GET_ORDERS_BY_COLLECTION_POINT = 'GET_ORDERS_BY_COLLECTION_POINT';
export const GET_ORDERS_BY_COLLECTION_POINT_START = 'GET_ORDERS_BY_COLLECTION_POINT_START';
export const GET_ORDERS_BY_COLLECTION_POINT_SUCCESS = 'GET_ORDERS_BY_COLLECTION_POINT_SUCCESS';
export const GET_ORDERS_BY_COLLECTION_POINT_FAIL = 'GET_ORDERS_BY_COLLECTION_POINT_FAIL';

export const UPDATE_ORDER = 'UPDATE_ORDER';
export const UPDATE_ORDER_START = 'UPDATE_ORDER_START';
export const UPDATE_ORDER_SUCCESS = 'UPDATE_ORDER_SUCCESS';
export const UPDATE_ORDER_FAIL = 'UPDATE_ORDER_FAIL';

export const FIND_BAR_STAFF = 'FIND_BAR_STAFF';
export const FIND_BAR_STAFF_START = 'FIND_BAR_STAFF_START';
export const FIND_BAR_STAFF_SUCCESS = 'FIND_BAR_STAFF_SUCCESS';
export const FIND_BAR_STAFF_FAIL = 'FIND_BAR_STAFF_FAIL';

export const NEW_ORDER = 'NEW_ORDER';
export const NEW_ORDER_START = 'NEW_ORDER_START';
export const NEW_ORDER_SUCCESS = 'NEW_ORDER_SUCCESS';
export const NEW_ORDER_FAIL = 'NEW_ORDER_FAIL';
