export const GET_ORDERS_BY_COLLECTION_POINT = 'GET_ORDERS_BY_COLLECTION_POINT';
export const GET_ORDERS_BY_COLLECTION_POINT_START = 'GET_ORDERS_BY_COLLECTION_POINT_START';
export const GET_ORDERS_BY_COLLECTION_POINT_SUCCESS = 'GET_ORDERS_BY_COLLECTION_POINT_SUCCESS';
export const GET_ORDERS_BY_COLLECTION_POINT_FAIL = 'GET_ORDERS_BY_COLLECTION_POINT_FAIL';

export const UPDATE_ORDER = 'UPDATE_ORDER';
export const UPDATE_ORDER_START = 'UPDATE_ORDER_START';
export const UPDATE_ORDER_SUCCESS = 'UPDATE_ORDER_SUCCESS';
export const UPDATE_ORDER_FAIL = 'UPDATE_ORDER_FAIL';

export const FIND_BAR_STAFF = 'FIND_BAR_STAFF';
export const FIND_BAR_STAFF_START = 'FIND_BAR_STAFF_START';
export const FIND_BAR_STAFF_SUCCESS = 'FIND_BAR_STAFF_SUCCESS';
export const FIND_BAR_STAFF_FAIL = 'FIND_BAR_STAFF_FAIL';

export const FIND_COLLECTION_POINTS = 'FIND_COLLECTION_POINTS';
export const FIND_COLLECTION_POINTS_START = 'FIND_COLLECTION_POINTS_START';
export const FIND_COLLECTION_POINTS_SUCCESS = 'FIND_COLLECTION_POINTS_SUCCESS';
export const FIND_COLLECTION_POINTS_FAIL = 'FIND_COLLECTION_POINTS_FAIL';