const OrderStatuses = {
    AWAITING_COLLECTION: "AWAITING_COLLECTION",
    IN_PROGRESS: "IN_PROGRESS",
    PENDING: "PENDING",
    AWAITING_USER_DECISION: "AWAITING_USER_DECISION",
    COMPLETED: "COMPLETED",
    REFUNDED: "REFUNDED",
    CANCELLED: "CANCELLED",
};

export default OrderStatuses;
