export const OrderStatuses = {
    AWAITING_COLLECTION: "AWAITING_COLLECTION",
    IN_PROGRESS: "IN_PROGRESS",
    PENDING: "PENDING",
    AWAITING_USER_DECISION: "AWAITING_USER_DECISION",
    COMPLETED: "COMPLETED",
    REFUNDED: "REFUNDED",
    CANCELLED: "CANCELLED",
};

export const IngredientAmounts = {
    FACTORY: 0,
    FILL: 1,
    SHOT: 2,
    DOUBLE_SHOT: 3,
    HALF_PINT: 4,
    PINT: 5,
    WINE_GLASS: 6,
};